// Code generated by ent, DO NOT EDIT.

package integrationupdate

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the integrationupdate type in the database.
	Label = "integration_update"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIntegration holds the string denoting the integration field in the database.
	FieldIntegration = "integration"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// FieldNewVersion holds the string denoting the new_version field in the database.
	FieldNewVersion = "new_version"
	// FieldRequestedBy holds the string denoting the requested_by field in the database.
	FieldRequestedBy = "requested_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// Table holds the table name of the integrationupdate in the database.
	Table = "integration_updates"
)

// Columns holds all SQL columns for integrationupdate fields.
var Columns = []string{
	FieldID,
	FieldIntegration,
	FieldState,
	FieldDetail,
	FieldNewVersion,
	FieldRequestedBy,
	FieldCreateTime,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IntegrationValidator is a validator for the "integration" field. It is called by the builders before save.
	IntegrationValidator func(string) error
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// State defines the type for the "state" enum field.
type State string

// StateRequested is the default value of the State enum.
const DefaultState = StateRequested

// State values.
const (
	StateRequested    State = "requested"
	StateAcknowledged State = "acknowledged"
	StateUpdating     State = "updating"
	StateCompleted    State = "completed"
	StateFailed       State = "failed"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateRequested, StateAcknowledged, StateUpdating, StateCompleted, StateFailed:
		return nil
	default:
		return fmt.Errorf("integrationupdate: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the IntegrationUpdate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIntegration orders the results by the integration field.
func ByIntegration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntegration, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByDetail orders the results by the detail field.
func ByDetail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetail, opts...).ToFunc()
}

// ByNewVersion orders the results by the new_version field.
func ByNewVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewVersion, opts...).ToFunc()
}

// ByRequestedBy orders the results by the requested_by field.
func ByRequestedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}
